/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.DaoDepartamento;
import fatec.poo.control.DaoFuncionarioHorista;
import fatec.poo.control.Conexao;
import fatec.poo.model.Departamento;
import fatec.poo.model.Funcionario;
import fatec.poo.model.FuncionarioHorista;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Fatec
 */
public class GuiFuncionarioHorista extends javax.swing.JFrame {

    /**
     * Creates new form GuiFuncionarioHorista
     */
    public GuiFuncionarioHorista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgrpSexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRegistro = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtDtAdmissao = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        txtValHorTrab = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rdbFeminino = new javax.swing.JRadioButton();
        rdbMasculino = new javax.swing.JRadioButton();
        txtSiglaDepartamento = new javax.swing.JTextField();
        btnConsultarDepartamento = new javax.swing.JButton();
        lblNomeDepartamento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Funcionário Horista");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Registro");

        jLabel2.setText("Nome");

        jLabel3.setText("Data de Admissão");

        jLabel4.setText("Cargo");

        jLabel5.setText("Valor Hora Trabalhada");

        txtNome.setEnabled(false);

        txtDtAdmissao.setEnabled(false);

        txtCargo.setEnabled(false);

        txtValHorTrab.setEnabled(false);

        jLabel6.setText("Sigla Departamento");

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));

        btgrpSexo.add(rdbFeminino);
        rdbFeminino.setSelected(true);
        rdbFeminino.setText("Feminino");
        rdbFeminino.setEnabled(false);

        btgrpSexo.add(rdbMasculino);
        rdbMasculino.setText("Masculino");
        rdbMasculino.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbFeminino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(rdbMasculino)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbFeminino)
                    .addComponent(rdbMasculino))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtSiglaDepartamento.setEnabled(false);

        btnConsultarDepartamento.setText("...");
        btnConsultarDepartamento.setEnabled(false);
        btnConsultarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarDepartamentoActionPerformed(evt);
            }
        });

        lblNomeDepartamento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDtAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(txtSiglaDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnConsultarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addComponent(txtValHorTrab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNomeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInserir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDtAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtValHorTrab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtSiglaDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConsultarDepartamento)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnInserir)
                    .addComponent(btnConsultar))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir, btnSair});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("","");
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@192.168.1.6:1521:xe");
        daoFuncHor = new DaoFuncionarioHorista(conexao.abrirConexao());  
        daoDepto = new DaoDepartamento(conexao.abrirConexao());
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        conexao.fecharConexao();
    }//GEN-LAST:event_formWindowClosed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
       funcHor = null;
       funcHor = daoFuncHor.consultar(Integer.parseInt(txtRegistro.getText()));
       
       if (funcHor == null){
           txtRegistro.setEnabled(false);
           txtNome.setEnabled(true);
           rdbFeminino.setEnabled(true);
           rdbMasculino.setEnabled(true);
           txtDtAdmissao.setEnabled(true);
           txtCargo.setEnabled(true);
           txtValHorTrab.setEnabled(true);
           txtSiglaDepartamento.setEnabled(true);
           btnConsultarDepartamento.setEnabled(true);
           txtNome.requestFocus();
           
           btnConsultar.setEnabled(false);
           btnInserir.setEnabled(true);
           btnAlterar.setEnabled(false);
           btnExcluir.setEnabled(false);
       }
       else{
          txtNome.setText(funcHor.getNome());
          if (funcHor.getSexo().equals("F")){
              rdbFeminino.setSelected(true);
          }else{
              rdbMasculino.setSelected(true);
          }
          txtDtAdmissao.setText(funcHor.getDtAdmissao());
          txtCargo.setText(funcHor.getCargo());
          txtValHorTrab.setText(String.valueOf(funcHor.getValHorTrab()));          
          txtSiglaDepartamento.setText(funcHor.getDepartamento().getSigla());
          lblNomeDepartamento.setText(funcHor.getDepartamento().getNome());
          
          txtRegistro.setEnabled(false);
          txtNome.setEnabled(true);
          rdbFeminino.setEnabled(true);
          rdbMasculino.setEnabled(true);
          txtDtAdmissao.setEnabled(true);
          txtCargo.setEnabled(true);
          txtValHorTrab.setEnabled(true);
          txtSiglaDepartamento.setEnabled(true);
          btnConsultarDepartamento.setEnabled(true);
          txtNome.requestFocus();
          
          btnConsultar.setEnabled(false);
          btnInserir.setEnabled(false);
          btnAlterar.setEnabled(true);
          btnExcluir.setEnabled(true);
       }    
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        funcHor = new FuncionarioHorista(Integer.parseInt(txtRegistro.getText()),
                                         txtNome.getText(),
                                         txtDtAdmissao.getText(),
                                         Double.parseDouble(txtValHorTrab.getText()));
        funcHor.setCargo(txtCargo.getText());
        if (rdbFeminino.isSelected()){
            funcHor.setSexo("F");
        }else{
            funcHor.setSexo("M");
        }
        
        //estabelece a associação binária bidirecional
        //entre funcionario horista e departamento        
        departamento.addFuncionario(funcHor); 
        daoFuncHor.inserir(funcHor);
         
        txtRegistro.setText(null);
        txtNome.setText(null); 
        rdbFeminino.setSelected(true);
        txtDtAdmissao.setText(null);
        txtCargo.setText(null);
        txtValHorTrab.setText(null);
        txtSiglaDepartamento.setText(null);
        lblNomeDepartamento.setText(null);
        txtRegistro.setEnabled(true);
        txtNome.setEnabled(false);
        rdbFeminino.setEnabled(false);
        rdbMasculino.setEnabled(false);
        txtDtAdmissao.setEnabled(false);
        txtCargo.setEnabled(false);
        txtValHorTrab.setEnabled(false);
        txtSiglaDepartamento.setEnabled(false);
        btnConsultarDepartamento.setEnabled(false);
        txtRegistro.requestFocus();
        
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
       if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?")== 0){//Sim
           funcHor.setNome(txtNome.getText());
           if (rdbFeminino.isSelected()){
               funcHor.setSexo("F");
           }else{
               funcHor.setSexo("M");
           }
           funcHor.setDtAdmissao(txtDtAdmissao.getText());
           funcHor.setCargo(txtCargo.getText());
           funcHor.setValHorTrab(Double.parseDouble(txtValHorTrab.getText()));
           
           //altera a associação binária bidirecional entre
           //funcionario horista e departamento  
           departamento.addFuncionario(funcHor);
              
           daoFuncHor.alterar(funcHor);           
        } 
       
        txtRegistro.setText(null);
        txtNome.setText(null); 
        rdbFeminino.setSelected(true);
        txtDtAdmissao.setText(null);
        txtCargo.setText(null);
        txtValHorTrab.setText(null);
        txtSiglaDepartamento.setText(null);
        lblNomeDepartamento.setText(null);
        txtRegistro.setEnabled(true);
        txtNome.setEnabled(false);
        rdbFeminino.setEnabled(false);
        rdbMasculino.setEnabled(false);
        txtDtAdmissao.setEnabled(false);
        txtCargo.setEnabled(false);
        txtValHorTrab.setEnabled(false);
        txtSiglaDepartamento.setEnabled(false);
        btnConsultarDepartamento.setEnabled(false);
        txtRegistro.requestFocus();
        
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Exclusão?") == 0){
            daoFuncHor.excluir(funcHor); 
            //departamentos.get(cbxDepartamentos.getSelectedIndex()).removeFuncionario(funcHor);
        }   
        txtRegistro.setText(null);
        txtNome.setText(null);     
        rdbFeminino.setSelected(true);
        txtDtAdmissao.setText(null);
        txtCargo.setText(null);
        txtValHorTrab.setText(null);
        txtSiglaDepartamento.setText(null);
        lblNomeDepartamento.setText(null);
        txtRegistro.setEnabled(true);
        txtNome.setEnabled(false);
        rdbFeminino.setEnabled(false);
        rdbMasculino.setEnabled(false);
        txtDtAdmissao.setEnabled(false);
        txtCargo.setEnabled(false);
        txtValHorTrab.setEnabled(false);
        txtSiglaDepartamento.setEnabled(false);
        btnConsultarDepartamento.setEnabled(false);
        txtRegistro.requestFocus();
        
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
           
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnConsultarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarDepartamentoActionPerformed
        departamento = daoDepto.consultar(txtSiglaDepartamento.getText());
        if (departamento == null){ //Não encontrou o objeto na base de dados
            JOptionPane.showMessageDialog(null, "Departamento não cadastrado");
            txtSiglaDepartamento.requestFocus();
            //txtSiglaDepartament.set        
        }else{//Encontrou o objeto na base de dados
            lblNomeDepartamento.setText(departamento.getNome());
        }
    }//GEN-LAST:event_btnConsultarDepartamentoActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgrpSexo;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultarDepartamento;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNomeDepartamento;
    private javax.swing.JRadioButton rdbFeminino;
    private javax.swing.JRadioButton rdbMasculino;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtDtAdmissao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRegistro;
    private javax.swing.JTextField txtSiglaDepartamento;
    private javax.swing.JTextField txtValHorTrab;
    // End of variables declaration//GEN-END:variables
    private Conexao conexao;
    private DaoFuncionarioHorista daoFuncHor;
    private DaoDepartamento daoDepto;
    private FuncionarioHorista funcHor;
    private Departamento departamento; 
}
